// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn7q6isyTJFZKYRE1W020eJkzX7HiZoC4',
    appId: '1:674442793356:web:9a907bf6cb0ceccb9246a9',
    messagingSenderId: '674442793356',
    projectId: 'simply-parked-9d54f',
    authDomain: 'simply-parked-9d54f.firebaseapp.com',
    storageBucket: 'simply-parked-9d54f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnDNSooikxwojmT0oBkujywAYIsBjakkc',
    appId: '1:674442793356:android:ca99596b7243d0609246a9',
    messagingSenderId: '674442793356',
    projectId: 'simply-parked-9d54f',
    storageBucket: 'simply-parked-9d54f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYaauyb2Ada4nKQEQLRD6S6MWq1ZuPzwI',
    appId: '1:674442793356:ios:f53cb513994178159246a9',
    messagingSenderId: '674442793356',
    projectId: 'simply-parked-9d54f',
    storageBucket: 'simply-parked-9d54f.appspot.com',
    iosBundleId: 'com.example.smartCarParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYaauyb2Ada4nKQEQLRD6S6MWq1ZuPzwI',
    appId: '1:674442793356:ios:f53cb513994178159246a9',
    messagingSenderId: '674442793356',
    projectId: 'simply-parked-9d54f',
    storageBucket: 'simply-parked-9d54f.appspot.com',
    iosBundleId: 'com.example.smartCarParking',
  );
}
